import Contact from "@src/components/Contact";
import Main from "@src/components/Main";
import OurService from "@src/components/OurService";
import Head from "next/head";


export default function Home() {
  return (
    <>
      <Head>
        <title>Degiya</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <OurService />
      <Contact />
    </>
  );
}
